# Generated by Django 3.2.5 on 2021-07-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('ENTERTAINMENT', 'Entertainment'), ('FASHION', 'Fashion'), ('TECH', 'Tech')], max_length=255, null=True),
        ),
    ]
